# Generated by Django 4.1.2 on 2022-10-27 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_EX',
            field=models.DateField(default=datetime.datetime(2022, 10, 27, 10, 31, 17, 870889)),
        ),
        migrations.AddField(
            model_name='article',
            name='article_created',
            field=models.DateField(default=datetime.datetime(2022, 10, 27, 10, 31, 17, 870889)),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_body',
            field=models.CharField(max_length=250),
        ),
    ]
